language: php

php:
    - '7.2'
    - '7.3'

services:
    - mysql

before_install:
    - mysql -e "create database IF NOT EXISTS database_bundle_test;"

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer update --optimize-autoloader
    - make php-cs-fixer@install

script:
    - make phpunit@run
    - make php-cs-fixer@run

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.1.*
    - SYMFONY_VERSION=4.2.*
    - SYMFONY_VERSION=4.3.*
